name: Sample docs export

on:
  push:
    branches:
      - main
    paths:
      - _example/big_example_ruleset.yaml
      - .github/workflows/sample-docs.yml

jobs:
  # This is faster than building
  generate-and-publish-html:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable
        run: curl -LO http://github.com/coffeemakingtoaster/whale-watcher/releases/download/pre-release/whale-watcher && chmod +x ./whale-watcher

      - name: Generate HTML
        run: ./whale-watcher docs --export ./_example/big_example_ruleset.yaml

      - name: Prep upload
        run: mkdir -p _out && mv ./index.html _out

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v3 
        id: deployment
        with:
          path: _out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      
      id-token: write   
    runs-on: ubuntu-latest
    needs: generate-and-publish-html
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
