name: Sample docs export

on:
  push:
    branches:
      - main
    paths:
      - ./_example/big_example_ruleset.yaml

jobs:
  # This is faster than building
  generate-and-publish-html:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable
        run: curl -LO http://github.com/coffeemakingtoaster/whale-watcher/releases/download/pre-release/whale-watcher && chmod +x ./whale-watcher

      - name: Generate HTML
        run: ./whale-watcher docs ./_example/big_example_ruleset.yaml

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v3 
        id: deployment
        with:
          path: ./index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
